#pragma once

#define MAX_GPU_CNT 32

#ifndef RCK_STEP_COUNT
#define RCK_STEP_COUNT 1000
#endif
#ifndef RCK_BLOCK_SIZE
#define RCK_BLOCK_SIZE 256
#endif
#ifndef RCK_POINT_GROUP_COUNT
#define RCK_POINT_GROUP_COUNT 24
#endif
#ifndef RCK_BLOCKS_PER_CU
#define RCK_BLOCKS_PER_CU 1
#endif
#ifndef RCK_GFX942_POINT_GROUP_COUNT
#define RCK_GFX942_POINT_GROUP_COUNT 24
#endif
#ifndef RCK_GFX950_POINT_GROUP_COUNT
#define RCK_GFX950_POINT_GROUP_COUNT 32
#endif
#ifndef RCK_GFX942_STEP_COUNT
#define RCK_GFX942_STEP_COUNT 1000
#endif
#ifndef RCK_GFX950_STEP_COUNT
#define RCK_GFX950_STEP_COUNT 2048
#endif
#ifndef RCK_KERNEL_A_TABLE_MODE
#define RCK_KERNEL_A_TABLE_MODE 0
#endif
#ifndef RCK_USE_ARCH_TABLE_DEFAULTS
#define RCK_USE_ARCH_TABLE_DEFAULTS 1
#endif
#ifndef RCK_GFX942_KERNEL_A_TABLE_MODE
#define RCK_GFX942_KERNEL_A_TABLE_MODE 0
#endif
#ifndef RCK_GFX950_KERNEL_A_TABLE_MODE
#define RCK_GFX950_KERNEL_A_TABLE_MODE 2
#endif
#ifndef RCK_STATE_LAYOUT
#define RCK_STATE_LAYOUT 0
#endif
#ifndef RCK_USE_ARCH_STATE_LAYOUT_DEFAULTS
#define RCK_USE_ARCH_STATE_LAYOUT_DEFAULTS 1
#endif
#ifndef RCK_GFX942_STATE_LAYOUT
#define RCK_GFX942_STATE_LAYOUT 0
#endif
#ifndef RCK_GFX950_STATE_LAYOUT
#define RCK_GFX950_STATE_LAYOUT 1
#endif

#define STEP_CNT RCK_STEP_COUNT
#define JMP_CNT 512
#define BLOCK_SIZE RCK_BLOCK_SIZE
#define PNT_GROUP_CNT RCK_POINT_GROUP_COUNT
#define BLOCKS_PER_CU RCK_BLOCKS_PER_CU

#if RCK_USE_ARCH_TABLE_DEFAULTS && defined(__gfx942__)
#define RCK_KERNEL_A_DEVICE_TABLE_MODE RCK_GFX942_KERNEL_A_TABLE_MODE
#elif RCK_USE_ARCH_TABLE_DEFAULTS && defined(__gfx950__)
#define RCK_KERNEL_A_DEVICE_TABLE_MODE RCK_GFX950_KERNEL_A_TABLE_MODE
#else
#define RCK_KERNEL_A_DEVICE_TABLE_MODE RCK_KERNEL_A_TABLE_MODE
#endif

#if RCK_USE_ARCH_STATE_LAYOUT_DEFAULTS && defined(__gfx942__)
#define RCK_DEVICE_STATE_LAYOUT RCK_GFX942_STATE_LAYOUT
#elif RCK_USE_ARCH_STATE_LAYOUT_DEFAULTS && defined(__gfx950__)
#define RCK_DEVICE_STATE_LAYOUT RCK_GFX950_STATE_LAYOUT
#else
#define RCK_DEVICE_STATE_LAYOUT RCK_STATE_LAYOUT
#endif

#if RCK_KERNEL_A_TABLE_MODE == 1
#define KERNEL_A_LDS_BYTES 0
#elif RCK_KERNEL_A_TABLE_MODE == 2
#define KERNEL_A_LDS_BYTES (16 * JMP_CNT * sizeof(u64))
#else
#define KERNEL_A_LDS_BYTES (8 * JMP_CNT * sizeof(u64))
#endif

#define TAME 0
#define WILD 1

#define GPU_DP_SIZE 48
#define MAX_DP_CNT (256 * 1024)
#define JMP_MASK (JMP_CNT - 1)
#define JMP_MASK_ADV (2048 - 1)
#define DPTABLE_MAX_CNT 16
#define MAX_CNT_LIST (512 * 1024)

#define DP_FLAG 0x0800
#define INV_FLAG 0x0200
#define JMP2_FLAG 0x0400

#define MD_LEN 10

// #define DEBUG_MODE
