// Inline-asm arithmetic primitives for CDNA3/CDNA4.
//
// GENERATED by tools/gen_asm.py - do not edit by hand, regenerate instead.
//
// See docs/CDNA_PHASE2_DESIGN.md for the reasoning and the measurements. In
// short: the hardware produces {carry, acc64} = a.u32 * b.u32 + acc64 in a
// single v_mad_u64_u32 with the carry delivered free into VCC, and the following
// v_addc_co_u32 consumes it as carry-in at zero wait states. C++ cannot express
// "consume that MAD's carry-out" and recovers it with a comparison instead,
// costing more than the carry the hardware already computed and discarded.
//
// Each carry chain is one asm block so nothing is scheduled inside it - an
// interposed instruction there forces a wait state, and those accounted for most
// of the overhead in the compiler-generated versions.
//
// License: GPLv3, see "LICENSE.TXT".

#pragma once


// 256x256 -> 512 bit multiply.
//
// Three-word accumulator: eight 32x32 products sum to at most ~2^67, so a 64-bit
// acc plus a few bits of ext is exactly what one column needs.
//
// The column shift stays in C++ because it needs the 32-bit halves of the
// accumulator, which an inline-asm 64-bit operand cannot address while
// v_mad_u64_u32 requires an even-aligned pair for it.
__device__ __forceinline__ void mul_256_to_512_asm(u64* rr, const u64* aa, const u64* bb)
{
    const u32* a = (const u32*)aa;
    const u32* b = (const u32*)bb;
    u32* r = (u32*)rr;
    u64 acc = 0;
    u32 ext = 0;
    // column 0: 1 product
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[0])
        : "vcc");
    r[0] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 1: 2 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[1]), "v"(a[1]), "v"(b[0])
        : "vcc");
    r[1] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 2: 3 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[2]), "v"(a[1]), "v"(b[1]), "v"(a[2]), "v"(b[0])
        : "vcc");
    r[2] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 3: 4 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[3]), "v"(a[1]), "v"(b[2]), "v"(a[2]), "v"(b[1]), "v"(a[3]), "v"(b[0])
        : "vcc");
    r[3] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 4: 5 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[4]), "v"(a[1]), "v"(b[3]), "v"(a[2]), "v"(b[2]), "v"(a[3]), "v"(b[1]), "v"(a[4]), "v"(b[0])
        : "vcc");
    r[4] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 5: 6 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[5]), "v"(a[1]), "v"(b[4]), "v"(a[2]), "v"(b[3]), "v"(a[3]), "v"(b[2]), "v"(a[4]), "v"(b[1]), "v"(a[5]), "v"(b[0])
        : "vcc");
    r[5] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 6: 7 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %14, %15, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[6]), "v"(a[1]), "v"(b[5]), "v"(a[2]), "v"(b[4]), "v"(a[3]), "v"(b[3]), "v"(a[4]), "v"(b[2]), "v"(a[5]), "v"(b[1]), "v"(a[6]), "v"(b[0])
        : "vcc");
    r[6] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 7: 8 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %14, %15, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %16, %17, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[0]), "v"(b[7]), "v"(a[1]), "v"(b[6]), "v"(a[2]), "v"(b[5]), "v"(a[3]), "v"(b[4]), "v"(a[4]), "v"(b[3]), "v"(a[5]), "v"(b[2]), "v"(a[6]), "v"(b[1]), "v"(a[7]), "v"(b[0])
        : "vcc");
    r[7] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 8: 7 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %14, %15, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[1]), "v"(b[7]), "v"(a[2]), "v"(b[6]), "v"(a[3]), "v"(b[5]), "v"(a[4]), "v"(b[4]), "v"(a[5]), "v"(b[3]), "v"(a[6]), "v"(b[2]), "v"(a[7]), "v"(b[1])
        : "vcc");
    r[8] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 9: 6 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[2]), "v"(b[7]), "v"(a[3]), "v"(b[6]), "v"(a[4]), "v"(b[5]), "v"(a[5]), "v"(b[4]), "v"(a[6]), "v"(b[3]), "v"(a[7]), "v"(b[2])
        : "vcc");
    r[9] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 10: 5 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[3]), "v"(b[7]), "v"(a[4]), "v"(b[6]), "v"(a[5]), "v"(b[5]), "v"(a[6]), "v"(b[4]), "v"(a[7]), "v"(b[3])
        : "vcc");
    r[10] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 11: 4 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[4]), "v"(b[7]), "v"(a[5]), "v"(b[6]), "v"(a[6]), "v"(b[5]), "v"(a[7]), "v"(b[4])
        : "vcc");
    r[11] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 12: 3 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[5]), "v"(b[7]), "v"(a[6]), "v"(b[6]), "v"(a[7]), "v"(b[5])
        : "vcc");
    r[12] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 13: 2 products
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[6]), "v"(b[7]), "v"(a[7]), "v"(b[6])
        : "vcc");
    r[13] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    // column 14: 1 product
    asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
        : "+v"(acc), "+v"(ext)
        : "v"(a[7]), "v"(b[7])
        : "vcc");
    r[14] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
    r[15] = (u32)acc;
}


// Reduce 512 bits mod p = 2^256 - 2^32 - 977, so 2^256 == 0x1000003D1 (mod p):
//
//   res = lo256 + hi256 * 0x1000003D1
//
// Two asm blocks. The first does all sixteen multiplies - v_mul_lo_u32 and
// v_mul_hi_u32 write single registers, sidestepping the even-aligned-pair
// requirement v_mad_u64_u32 imposes on its 64-bit addend, and neither touches
// VCC. The second is one uninterrupted carry chain; keeping the multiplies out
// of it avoids the wait states an interposed instruction forces.
//
// 977 < 2^10, so every high half here is at most 977.
//
// The result is in [0, 2^256), NOT reduced to [0, p) - RC's lazy convention,
// which every consumer here tolerates.
__device__ __forceinline__ void reduce_512_to_256_asm(u64* res, const u64* buff)
{
    const u32* lo = (const u32*)buff;
    const u32* hi = (const u32*)(buff + 4);
    u32* r = (u32*)res;
    const u32 c977 = P_INV32;
    u32 pl[8], ph[8], t[9], t9, ovl, ovh;

    asm volatile(
            "v_mul_lo_u32 %0, %16, %24\n\t"
            "v_mul_hi_u32 %8, %16, %24\n\t"
            "v_mul_lo_u32 %1, %17, %24\n\t"
            "v_mul_hi_u32 %9, %17, %24\n\t"
            "v_mul_lo_u32 %2, %18, %24\n\t"
            "v_mul_hi_u32 %10, %18, %24\n\t"
            "v_mul_lo_u32 %3, %19, %24\n\t"
            "v_mul_hi_u32 %11, %19, %24\n\t"
            "v_mul_lo_u32 %4, %20, %24\n\t"
            "v_mul_hi_u32 %12, %20, %24\n\t"
            "v_mul_lo_u32 %5, %21, %24\n\t"
            "v_mul_hi_u32 %13, %21, %24\n\t"
            "v_mul_lo_u32 %6, %22, %24\n\t"
            "v_mul_hi_u32 %14, %22, %24\n\t"
            "v_mul_lo_u32 %7, %23, %24\n\t"
            "v_mul_hi_u32 %15, %23, %24\n\t"
        : "=&v"(pl[0]), "=&v"(pl[1]), "=&v"(pl[2]), "=&v"(pl[3]), "=&v"(pl[4]), "=&v"(pl[5]), "=&v"(pl[6]), "=&v"(pl[7]), "=&v"(ph[0]), "=&v"(ph[1]), "=&v"(ph[2]), "=&v"(ph[3]), "=&v"(ph[4]), "=&v"(ph[5]), "=&v"(ph[6]), "=&v"(ph[7])
        : "v"(hi[0]), "v"(hi[1]), "v"(hi[2]), "v"(hi[3]), "v"(hi[4]), "v"(hi[5]), "v"(hi[6]), "v"(hi[7]), "v"(c977));

    asm volatile(
            "v_add_co_u32  %8, vcc, %20, %27\n\t"
            "v_addc_co_u32 %9, vcc, %21, %28, vcc\n\t"
            "v_addc_co_u32 %10, vcc, %22, %29, vcc\n\t"
            "v_addc_co_u32 %11, vcc, %23, %30, vcc\n\t"
            "v_addc_co_u32 %12, vcc, %24, %31, vcc\n\t"
            "v_addc_co_u32 %13, vcc, %25, %32, vcc\n\t"
            "v_addc_co_u32 %14, vcc, %26, %33, vcc\n\t"
            "v_addc_co_u32 %15, vcc, %34, 0, vcc\n\t"
            "v_add_co_u32  %8, vcc, %8, %35\n\t"
            "v_addc_co_u32 %9, vcc, %9, %36, vcc\n\t"
            "v_addc_co_u32 %10, vcc, %10, %37, vcc\n\t"
            "v_addc_co_u32 %11, vcc, %11, %38, vcc\n\t"
            "v_addc_co_u32 %12, vcc, %12, %39, vcc\n\t"
            "v_addc_co_u32 %13, vcc, %13, %40, vcc\n\t"
            "v_addc_co_u32 %14, vcc, %14, %41, vcc\n\t"
            "v_addc_co_u32 %15, vcc, %15, %42, vcc\n\t"
            "v_addc_co_u32 %16, vcc, 0, 0, vcc\n\t"
            "v_add_co_u32  %0, vcc, %43, %19\n\t"
            "v_addc_co_u32 %1, vcc, %44, %8, vcc\n\t"
            "v_addc_co_u32 %2, vcc, %45, %9, vcc\n\t"
            "v_addc_co_u32 %3, vcc, %46, %10, vcc\n\t"
            "v_addc_co_u32 %4, vcc, %47, %11, vcc\n\t"
            "v_addc_co_u32 %5, vcc, %48, %12, vcc\n\t"
            "v_addc_co_u32 %6, vcc, %49, %13, vcc\n\t"
            "v_addc_co_u32 %7, vcc, %50, %14, vcc\n\t"
            "v_addc_co_u32 %17, vcc, %15, 0, vcc\n\t"
            "v_addc_co_u32 %18, vcc, %16, 0, vcc\n\t"
        : "=&v"(r[0]), "=&v"(r[1]), "=&v"(r[2]), "=&v"(r[3]), "=&v"(r[4]), "=&v"(r[5]), "=&v"(r[6]), "=&v"(r[7]), "=&v"(t[1]), "=&v"(t[2]), "=&v"(t[3]), "=&v"(t[4]), "=&v"(t[5]), "=&v"(t[6]), "=&v"(t[7]), "=&v"(t[8]), "=&v"(t9), "=&v"(ovl), "=&v"(ovh)
        : "v"(pl[0]), "v"(pl[1]), "v"(pl[2]), "v"(pl[3]), "v"(pl[4]), "v"(pl[5]), "v"(pl[6]), "v"(pl[7]), "v"(ph[0]), "v"(ph[1]), "v"(ph[2]), "v"(ph[3]), "v"(ph[4]), "v"(ph[5]), "v"(ph[6]), "v"(ph[7]), "v"(hi[0]), "v"(hi[1]), "v"(hi[2]), "v"(hi[3]), "v"(hi[4]), "v"(hi[5]), "v"(hi[6]), "v"(hi[7]), "v"(lo[0]), "v"(lo[1]), "v"(lo[2]), "v"(lo[3]), "v"(lo[4]), "v"(lo[5]), "v"(lo[6]), "v"(lo[7])
        : "vcc");

    // Second fold: ov * (2^32 + 977) < 2^67, so three words.
    u64 ov = ((u64)ovh << 32) | ovl;
    u128 f = (u128)ov * (u128)P0_INV_FULL;
    u32 c = 0;
    r[0] = adc32(r[0], (u32)f, &c);
    r[1] = adc32(r[1], (u32)(f >> 32), &c);
    r[2] = adc32(r[2], (u32)(f >> 64), &c);
    #pragma unroll
    for (int k = 3; k < 8; k++) r[k] = adc32(r[k], 0, &c);

    // Third fold: at most one bit escaped, worth 0x1000003D1. Uniformly not
    // taken across a wave in practice. Unlike RC's reference we fold it back
    // rather than discard it - discarding is wrong by 2^256 when it happens.
    if (c)
    {
        u32 c2 = 0;
        r[0] = adc32(r[0], (u32)P_INV32, &c2);
        r[1] = adc32(r[1], 1u, &c2);
        #pragma unroll
        for (int k = 2; k < 8; k++) r[k] = adc32(r[k], 0, &c2);
    }
    (void)t; (void)t9;
}


// res = (val1 - val2) mod p, branchless.
//
// One borrow chain, the borrow captured as a lane mask, then one masked add-back
// of p. The reference applies that correction under a data-dependent
// `if (borrow)`, which costs a wave divergence on every call - and this runs
// seven times per point addition. p's upper six 32-bit limbs are all ones, so
// `p & mask` is just the mask there; only limbs 0 and 1 need an explicit AND.
//
// INPUT CONTRACT: operands in [0, p), not merely [0, 2^256) - a single
// correction has to suffice. See the note in RCGpuUtils_cdna.h.
__device__ __forceinline__ void SubModP_asm(u64* res, const u64* val1, const u64* val2)
{
    const u32* a = (const u32*)val1;
    const u32* b = (const u32*)val2;
    u32* r = (u32*)res;
    u32 mask, t0, t1;
    asm volatile(
            "v_sub_co_u32  %0, vcc, %11, %19\n\t"
            "v_subb_co_u32 %1, vcc, %12, %20, vcc\n\t"
            "v_subb_co_u32 %2, vcc, %13, %21, vcc\n\t"
            "v_subb_co_u32 %3, vcc, %14, %22, vcc\n\t"
            "v_subb_co_u32 %4, vcc, %15, %23, vcc\n\t"
            "v_subb_co_u32 %5, vcc, %16, %24, vcc\n\t"
            "v_subb_co_u32 %6, vcc, %17, %25, vcc\n\t"
            "v_subb_co_u32 %7, vcc, %18, %26, vcc\n\t"
            "v_cndmask_b32 %8, 0, -1, vcc\n\t"
            "v_and_b32     %9, 0xFFFFFC2F, %8\n\t"
            "v_and_b32     %10, 0xFFFFFFFE, %8\n\t"
            "v_add_co_u32  %0, vcc, %0, %9\n\t"
            "v_addc_co_u32 %1, vcc, %1, %10, vcc\n\t"
            "v_addc_co_u32 %2, vcc, %2, %8, vcc\n\t"
            "v_addc_co_u32 %3, vcc, %3, %8, vcc\n\t"
            "v_addc_co_u32 %4, vcc, %4, %8, vcc\n\t"
            "v_addc_co_u32 %5, vcc, %5, %8, vcc\n\t"
            "v_addc_co_u32 %6, vcc, %6, %8, vcc\n\t"
            "v_addc_co_u32 %7, vcc, %7, %8, vcc\n\t"
        : "=&v"(r[0]), "=&v"(r[1]), "=&v"(r[2]), "=&v"(r[3]), "=&v"(r[4]), "=&v"(r[5]), "=&v"(r[6]), "=&v"(r[7]), "=&v"(mask), "=&v"(t0), "=&v"(t1)
        : "v"(a[0]), "v"(a[1]), "v"(a[2]), "v"(a[3]), "v"(a[4]), "v"(a[5]), "v"(a[6]), "v"(a[7]), "v"(b[0]), "v"(b[1]), "v"(b[2]), "v"(b[3]), "v"(b[4]), "v"(b[5]), "v"(b[6]), "v"(b[7])
        : "vcc");
}

