// 256x256 -> 512 bit multiply for CDNA3/CDNA4, Comba column scanning.
//
// GENERATED by tools/gen_mul_asm.py - do not edit by hand, regenerate instead.
//
// See docs/CDNA_PHASE2_DESIGN.md for why this is assembly. In short: the hardware
// produces {carry, acc64} = a.u32 * b.u32 + acc64 in a single v_mad_u64_u32 with
// the carry delivered free into VCC, and the following v_addc_co_u32 consumes it
// as carry-in at zero wait states. C++ cannot express "consume that MAD's
// carry-out" and recovers it with a comparison instead, which costs more than the
// carry the hardware already computed and discarded.
//
// Each column is one asm block so nothing is scheduled inside its carry chain -
// an interposed instruction there forces a wait state, and those accounted for
// most of the overhead in the compiler-generated version.
//
// License: GPLv3, see "LICENSE.TXT".

#pragma once

__device__ __forceinline__ void mul_256_to_512_asm(u64* rr, const u64* aa, const u64* bb)
{
    const u32* a = (const u32*)aa;
    const u32* b = (const u32*)bb;
    u32* r = (u32*)rr;

    // Three-word accumulator. Eight 32x32 products sum to at most ~2^67, so the
    // 64-bit acc plus a few bits of ext is exactly what a column needs.
    u64 acc = 0;
    u32 ext = 0;

    {
        // column 0: 1 product
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[0])
            : "vcc");
        r[0] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 1: 2 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[1]), "v"(a[1]), "v"(b[0])
            : "vcc");
        r[1] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 2: 3 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[2]), "v"(a[1]), "v"(b[1]), "v"(a[2]), "v"(b[0])
            : "vcc");
        r[2] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 3: 4 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[3]), "v"(a[1]), "v"(b[2]), "v"(a[2]), "v"(b[1]), "v"(a[3]), "v"(b[0])
            : "vcc");
        r[3] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 4: 5 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[4]), "v"(a[1]), "v"(b[3]), "v"(a[2]), "v"(b[2]), "v"(a[3]), "v"(b[1]), "v"(a[4]), "v"(b[0])
            : "vcc");
        r[4] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 5: 6 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[5]), "v"(a[1]), "v"(b[4]), "v"(a[2]), "v"(b[3]), "v"(a[3]), "v"(b[2]), "v"(a[4]), "v"(b[1]), "v"(a[5]), "v"(b[0])
            : "vcc");
        r[5] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 6: 7 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %14, %15, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[6]), "v"(a[1]), "v"(b[5]), "v"(a[2]), "v"(b[4]), "v"(a[3]), "v"(b[3]), "v"(a[4]), "v"(b[2]), "v"(a[5]), "v"(b[1]), "v"(a[6]), "v"(b[0])
            : "vcc");
        r[6] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 7: 8 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %14, %15, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %16, %17, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[0]), "v"(b[7]), "v"(a[1]), "v"(b[6]), "v"(a[2]), "v"(b[5]), "v"(a[3]), "v"(b[4]), "v"(a[4]), "v"(b[3]), "v"(a[5]), "v"(b[2]), "v"(a[6]), "v"(b[1]), "v"(a[7]), "v"(b[0])
            : "vcc");
        r[7] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 8: 7 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %14, %15, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[1]), "v"(b[7]), "v"(a[2]), "v"(b[6]), "v"(a[3]), "v"(b[5]), "v"(a[4]), "v"(b[4]), "v"(a[5]), "v"(b[3]), "v"(a[6]), "v"(b[2]), "v"(a[7]), "v"(b[1])
            : "vcc");
        r[8] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 9: 6 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %12, %13, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[2]), "v"(b[7]), "v"(a[3]), "v"(b[6]), "v"(a[4]), "v"(b[5]), "v"(a[5]), "v"(b[4]), "v"(a[6]), "v"(b[3]), "v"(a[7]), "v"(b[2])
            : "vcc");
        r[9] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 10: 5 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %10, %11, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[3]), "v"(b[7]), "v"(a[4]), "v"(b[6]), "v"(a[5]), "v"(b[5]), "v"(a[6]), "v"(b[4]), "v"(a[7]), "v"(b[3])
            : "vcc");
        r[10] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 11: 4 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %8, %9, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[4]), "v"(b[7]), "v"(a[5]), "v"(b[6]), "v"(a[6]), "v"(b[5]), "v"(a[7]), "v"(b[4])
            : "vcc");
        r[11] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 12: 3 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %6, %7, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[5]), "v"(b[7]), "v"(a[6]), "v"(b[6]), "v"(a[7]), "v"(b[5])
            : "vcc");
        r[12] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 13: 2 products
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            "v_mad_u64_u32 %0, vcc, %4, %5, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[6]), "v"(b[7]), "v"(a[7]), "v"(b[6])
            : "vcc");
        r[13] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
        // column 14: 1 product
        asm volatile(
            "v_mad_u64_u32 %0, vcc, %2, %3, %0\n\t"
            "v_addc_co_u32 %1, vcc, 0, %1, vcc\n\t"
            : "+v"(acc), "+v"(ext)
            : "v"(a[7]), "v"(b[7])
            : "vcc");
        r[14] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
    }
    r[15] = (u32)acc;
}

