#!/usr/bin/env python3
"""Generate the inline-asm arithmetic primitives for include/cdna/asm_primitives.h.

Why generated rather than hand-written: the 256x256->512 multiply alone is 64
products x 2 instructions with a carry threaded through every pair. That is
exactly the shape where a transcription slip produces silently wrong keys rather
than a compile error, and where a regenerable source beats hand formatting.

Why assembly at all (see docs/CDNA_PHASE2_DESIGN.md): the hardware computes
  {carry, acc64} = a.u32 * b.u32 + acc64
in one v_mad_u64_u32 and hands the carry to VCC for free, where the next
instruction consumes it as carry-in at zero wait states. C++ has no way to
consume a multiply-accumulate's carry-out, so the compiler recovers it with a
comparison - which is why a pure-C++ Comba rewrite measured worse than operand
scanning despite eliminating the register moves.

The recurring constraint throughout: v_mad_u64_u32 needs an even-aligned VGPR
pair for its 64-bit addend, and inline-asm operands cannot address the halves of
a 64-bit operand. That forces a sliding accumulator in the multiply (whose column
shifts stay in C++), and is why the reduction uses v_mul_lo_u32/v_mul_hi_u32
instead - those write single registers.

Usage: tools/gen_asm.py > include/cdna/asm_primitives.h
"""

LIMBS = 8                 # 32-bit limbs in a 256-bit value
COLS = 2 * LIMBS - 1
NL = '\\n\\t'             # emitted into the C string literal, not interpreted here

HEADER = '''// Inline-asm arithmetic primitives for CDNA3/CDNA4.
//
// GENERATED by tools/gen_asm.py - do not edit by hand, regenerate instead.
//
// See docs/CDNA_PHASE2_DESIGN.md for the reasoning and the measurements. In
// short: the hardware produces {carry, acc64} = a.u32 * b.u32 + acc64 in a
// single v_mad_u64_u32 with the carry delivered free into VCC, and the following
// v_addc_co_u32 consumes it as carry-in at zero wait states. C++ cannot express
// "consume that MAD's carry-out" and recovers it with a comparison instead,
// costing more than the carry the hardware already computed and discarded.
//
// Each carry chain is one asm block so nothing is scheduled inside it - an
// interposed instruction there forces a wait state, and those accounted for most
// of the overhead in the compiler-generated versions.
//
// License: GPLv3, see "LICENSE.TXT".

#pragma once
'''


def multiply():
    """Comba column-scanning 256x256 -> 512 multiply."""
    out = ['''
// 256x256 -> 512 bit multiply.
//
// Three-word accumulator: eight 32x32 products sum to at most ~2^67, so a 64-bit
// acc plus a few bits of ext is exactly what one column needs.
//
// The column shift stays in C++ because it needs the 32-bit halves of the
// accumulator, which an inline-asm 64-bit operand cannot address while
// v_mad_u64_u32 requires an even-aligned pair for it.
__device__ __forceinline__ void mul_256_to_512_asm(u64* rr, const u64* aa, const u64* bb)
{
    const u32* a = (const u32*)aa;
    const u32* b = (const u32*)bb;
    u32* r = (u32*)rr;
    u64 acc = 0;
    u32 ext = 0;
''']
    for col in range(COLS):
        pairs = [(i, col - i) for i in range(max(0, col - LIMBS + 1), min(LIMBS - 1, col) + 1)]
        lines = []
        for n, (i, j) in enumerate(pairs):
            ai, bj = 2 + 2 * n, 3 + 2 * n
            lines.append('"v_mad_u64_u32 %%0, vcc, %%%d, %%%d, %%0%s"' % (ai, bj, NL))
            lines.append('"v_addc_co_u32 %%1, vcc, 0, %%1, vcc%s"' % NL)
        ins = ", ".join('"v"(a[%d]), "v"(b[%d])' % (i, j) for i, j in pairs)
        body = "\n            ".join(lines)
        plural = "s" if len(pairs) != 1 else ""
        out.append('''    // column %d: %d product%s
    asm volatile(
            %s
        : "+v"(acc), "+v"(ext)
        : %s
        : "vcc");
    r[%d] = (u32)acc;
    acc = (acc >> 32) | ((u64)ext << 32);
    ext = 0;
''' % (col, len(pairs), plural, body, ins, col))
    out.append('''    r[15] = (u32)acc;
}
''')
    return "".join(out)


def reduction():
    """Reduce 512 bits mod p, exploiting 2^256 == 2^32 + 977."""
    b1 = []
    for i in range(8):
        b1.append('"v_mul_lo_u32 %%%d, %%%d, %%24%s"' % (i, 16 + i, NL))
        b1.append('"v_mul_hi_u32 %%%d, %%%d, %%24%s"' % (8 + i, 16 + i, NL))
    o1 = ", ".join(['"=&v"(pl[%d])' % i for i in range(8)]
                   + ['"=&v"(ph[%d])' % i for i in range(8)])
    i1 = ", ".join(['"v"(hi[%d])' % i for i in range(8)] + ['"v"(c977)'])

    T = dict((i, 8 + (i - 1)) for i in range(1, 9))
    T9, OVL, OVH = 16, 17, 18
    PL = [19 + i for i in range(8)]
    PH = [27 + i for i in range(8)]
    HI = [35 + i for i in range(8)]
    LO = [43 + i for i in range(8)]
    b2 = []
    b2.append('"v_add_co_u32  %%%d, vcc, %%%d, %%%d%s"' % (T[1], PL[1], PH[0], NL))
    for i in range(2, 8):
        b2.append('"v_addc_co_u32 %%%d, vcc, %%%d, %%%d, vcc%s"' % (T[i], PL[i], PH[i - 1], NL))
    b2.append('"v_addc_co_u32 %%%d, vcc, %%%d, 0, vcc%s"' % (T[8], PH[7], NL))
    b2.append('"v_add_co_u32  %%%d, vcc, %%%d, %%%d%s"' % (T[1], T[1], HI[0], NL))
    for i in range(2, 9):
        b2.append('"v_addc_co_u32 %%%d, vcc, %%%d, %%%d, vcc%s"' % (T[i], T[i], HI[i - 1], NL))
    b2.append('"v_addc_co_u32 %%%d, vcc, 0, 0, vcc%s"' % (T9, NL))
    b2.append('"v_add_co_u32  %%0, vcc, %%%d, %%%d%s"' % (LO[0], PL[0], NL))
    for i in range(1, 8):
        b2.append('"v_addc_co_u32 %%%d, vcc, %%%d, %%%d, vcc%s"' % (i, LO[i], T[i], NL))
    b2.append('"v_addc_co_u32 %%%d, vcc, %%%d, 0, vcc%s"' % (OVL, T[8], NL))
    b2.append('"v_addc_co_u32 %%%d, vcc, %%%d, 0, vcc%s"' % (OVH, T9, NL))
    o2 = ", ".join(['"=&v"(r[%d])' % i for i in range(8)]
                   + ['"=&v"(t[%d])' % i for i in range(1, 9)]
                   + ['"=&v"(t9)', '"=&v"(ovl)', '"=&v"(ovh)'])
    i2 = ", ".join(['"v"(pl[%d])' % i for i in range(8)]
                   + ['"v"(ph[%d])' % i for i in range(8)]
                   + ['"v"(hi[%d])' % i for i in range(8)]
                   + ['"v"(lo[%d])' % i for i in range(8)])

    return '''
// Reduce 512 bits mod p = 2^256 - 2^32 - 977, so 2^256 == 0x1000003D1 (mod p):
//
//   res = lo256 + hi256 * 0x1000003D1
//
// Two asm blocks. The first does all sixteen multiplies - v_mul_lo_u32 and
// v_mul_hi_u32 write single registers, sidestepping the even-aligned-pair
// requirement v_mad_u64_u32 imposes on its 64-bit addend, and neither touches
// VCC. The second is one uninterrupted carry chain; keeping the multiplies out
// of it avoids the wait states an interposed instruction forces.
//
// 977 < 2^10, so every high half here is at most 977.
//
// The result is in [0, 2^256), NOT reduced to [0, p) - RC's lazy convention,
// which every consumer here tolerates.
__device__ __forceinline__ void reduce_512_to_256_asm(u64* res, const u64* buff)
{
    const u32* lo = (const u32*)buff;
    const u32* hi = (const u32*)(buff + 4);
    u32* r = (u32*)res;
    const u32 c977 = P_INV32;
    u32 pl[8], ph[8], t[9], t9, ovl, ovh;

    asm volatile(
            %s
        : %s
        : %s);

    asm volatile(
            %s
        : %s
        : %s
        : "vcc");

    // Second fold: ov * (2^32 + 977) < 2^67, so three words.
    u64 ov = ((u64)ovh << 32) | ovl;
    u128 f = (u128)ov * (u128)P0_INV_FULL;
    u32 c = 0;
    r[0] = adc32(r[0], (u32)f, &c);
    r[1] = adc32(r[1], (u32)(f >> 32), &c);
    r[2] = adc32(r[2], (u32)(f >> 64), &c);
    #pragma unroll
    for (int k = 3; k < 8; k++) r[k] = adc32(r[k], 0, &c);

    // Third fold: at most one bit escaped, worth 0x1000003D1. Uniformly not
    // taken across a wave in practice. Unlike RC's reference we fold it back
    // rather than discard it - discarding is wrong by 2^256 when it happens.
    if (c)
    {
        u32 c2 = 0;
        r[0] = adc32(r[0], (u32)P_INV32, &c2);
        r[1] = adc32(r[1], 1u, &c2);
        #pragma unroll
        for (int k = 2; k < 8; k++) r[k] = adc32(r[k], 0, &c2);
    }
    (void)t; (void)t9;
}
''' % ("\n            ".join(b1), o1, i1, "\n            ".join(b2), o2, i2)


def submodp():
    """Branchless modular subtract."""
    R = list(range(8))
    M, T0, T1 = 8, 9, 10
    A = [11 + i for i in range(8)]
    B = [19 + i for i in range(8)]
    L = ['"v_sub_co_u32  %%%d, vcc, %%%d, %%%d%s"' % (R[0], A[0], B[0], NL)]
    for i in range(1, 8):
        L.append('"v_subb_co_u32 %%%d, vcc, %%%d, %%%d, vcc%s"' % (R[i], A[i], B[i], NL))
    L.append('"v_cndmask_b32 %%%d, 0, -1, vcc%s"' % (M, NL))
    L.append('"v_and_b32     %%%d, 0xFFFFFC2F, %%%d%s"' % (T0, M, NL))
    L.append('"v_and_b32     %%%d, 0xFFFFFFFE, %%%d%s"' % (T1, M, NL))
    L.append('"v_add_co_u32  %%%d, vcc, %%%d, %%%d%s"' % (R[0], R[0], T0, NL))
    L.append('"v_addc_co_u32 %%%d, vcc, %%%d, %%%d, vcc%s"' % (R[1], R[1], T1, NL))
    for i in range(2, 8):
        L.append('"v_addc_co_u32 %%%d, vcc, %%%d, %%%d, vcc%s"' % (R[i], R[i], M, NL))
    outs = ", ".join(['"=&v"(r[%d])' % i for i in range(8)]
                     + ['"=&v"(mask)', '"=&v"(t0)', '"=&v"(t1)'])
    ins = ", ".join(['"v"(a[%d])' % i for i in range(8)]
                    + ['"v"(b[%d])' % i for i in range(8)])
    return '''
// res = (val1 - val2) mod p, branchless.
//
// One borrow chain, the borrow captured as a lane mask, then one masked add-back
// of p. The reference applies that correction under a data-dependent
// `if (borrow)`, which costs a wave divergence on every call - and this runs
// seven times per point addition. p's upper six 32-bit limbs are all ones, so
// `p & mask` is just the mask there; only limbs 0 and 1 need an explicit AND.
//
// INPUT CONTRACT: operands in [0, p), not merely [0, 2^256) - a single
// correction has to suffice. See the note in RCGpuUtils_cdna.h.
__device__ __forceinline__ void SubModP_asm(u64* res, const u64* val1, const u64* val2)
{
    const u32* a = (const u32*)val1;
    const u32* b = (const u32*)val2;
    u32* r = (u32*)res;
    u32 mask, t0, t1;
    asm volatile(
            %s
        : %s
        : %s
        : "vcc");
}
''' % ("\n            ".join(L), outs, ins)


def main():
    print(HEADER)
    print(multiply())
    print(reduction())
    print(submodp())


if __name__ == '__main__':
    main()
