#!/usr/bin/env python3
"""Generate the inline-asm Comba multiply for include/cdna/mul256_asm.h.

Why generated rather than hand-written: the 256x256->512 multiply is 64 products
x 2 instructions with a carry dependency threaded through every pair. That is
exactly the shape where a transcription slip produces silently wrong keys rather
than a compile error, and where a regenerable source is worth more than hand
formatting.

Why assembly at all (see docs/CDNA_PHASE2_DESIGN.md): the hardware computes
  {carry, acc64} = a.u32 * b.u32 + acc64
in one instruction and hands the carry to VCC for free, where the next
instruction consumes it as carry-in at 0 wait states. C++ has no way to consume a
multiply-accumulate's carry-out, so the compiler recovers it with a comparison -
which is why the pure-C++ Comba version measured worse than operand scanning
despite eliminating the register moves.

Each Comba column becomes one asm block, so nothing gets scheduled inside its
carry chain. The column shift stays in C++: it needs the 32-bit halves of the
accumulator, and inline-asm operands cannot address the halves of a 64-bit
operand while v_mad_u64_u32 requires an even-aligned pair for it.

Usage: tools/gen_mul_asm.py > include/cdna/mul256_asm.h
"""

LIMBS = 8          # 32-bit limbs in a 256-bit value
COLS = 2 * LIMBS - 1


def column_block(col):
    """One Comba column: every product a[i]*b[col-i], accumulated with its carry."""
    pairs = [(i, col - i) for i in range(max(0, col - LIMBS + 1), min(LIMBS - 1, col) + 1)]

    # %0 = acc (u64, aligned pair), %1 = ext, then the a/b limbs as inputs.
    lines = []
    for n, (i, j) in enumerate(pairs):
        ai, bj = 2 + 2 * n, 3 + 2 * n
        lines.append(f'"v_mad_u64_u32 %0, vcc, %{ai}, %{bj}, %0\\n\\t"')
        lines.append(f'"v_addc_co_u32 %1, vcc, 0, %1, vcc\\n\\t"')

    ins = ", ".join(f'"v"(a[{i}]), "v"(b[{j}])' for i, j in pairs)
    body = "\n            ".join(lines)
    return f'''        // column {col}: {len(pairs)} product{"s" if len(pairs) != 1 else ""}
        asm volatile(
            {body}
            : "+v"(acc), "+v"(ext)
            : {ins}
            : "vcc");
        r[{col}] = (u32)acc;
        acc = (acc >> 32) | ((u64)ext << 32);
        ext = 0;
'''


def main():
    out = []
    out.append('''// 256x256 -> 512 bit multiply for CDNA3/CDNA4, Comba column scanning.
//
// GENERATED by tools/gen_mul_asm.py - do not edit by hand, regenerate instead.
//
// See docs/CDNA_PHASE2_DESIGN.md for why this is assembly. In short: the hardware
// produces {carry, acc64} = a.u32 * b.u32 + acc64 in a single v_mad_u64_u32 with
// the carry delivered free into VCC, and the following v_addc_co_u32 consumes it
// as carry-in at zero wait states. C++ cannot express "consume that MAD's
// carry-out" and recovers it with a comparison instead, which costs more than the
// carry the hardware already computed and discarded.
//
// Each column is one asm block so nothing is scheduled inside its carry chain -
// an interposed instruction there forces a wait state, and those accounted for
// most of the overhead in the compiler-generated version.
//
// License: GPLv3, see "LICENSE.TXT".

#pragma once

__device__ __forceinline__ void mul_256_to_512_asm(u64* rr, const u64* aa, const u64* bb)
{
    const u32* a = (const u32*)aa;
    const u32* b = (const u32*)bb;
    u32* r = (u32*)rr;

    // Three-word accumulator. Eight 32x32 products sum to at most ~2^67, so the
    // 64-bit acc plus a few bits of ext is exactly what a column needs.
    u64 acc = 0;
    u32 ext = 0;

    {
''')
    for col in range(COLS):
        out.append(column_block(col))
    out.append('''    }
    r[15] = (u32)acc;
}
''')
    print("".join(out))


if __name__ == '__main__':
    main()
